- lua/diffview/git.lua
Don't list untracked files if `status.showUntrackedFiles` is set to `false` in git config.
> fix(git): Respect git config for status of untracked files.

- README.md
- doc/diffview.txt
- lua/diffview/arg-parser.lua
- lua/diffview/git.lua
- lua/diffview/lib.lua
- lua/diffview/view.lua
Fixes #10.
This adds an optional arg to either enable or disable showing untracked files. If you provide this flag, Diffview will ignore your local setting for `status.showUntrackedFiles`.
```
:DiffviewOpen [git-rev] [args] [ -- {paths...}]
...
Args:
-u[value], --untracked-files[={value}]
Specify whether or not to show untracked files. If
flag is given without value; defaults to `true`.
{value} can be one of:
- `true`, `normal`, `all` Show untracked.
- `false`, `no` Don't show untracked.
```
Example usage:
```
:DiffviewOpen HEAD~2 -uno
:DiffviewOpen HEAD~2 --untracked-files=all
```
> feat: Optionally hide untracked files.

- lua/diffview.lua
- lua/diffview/arg-parser.lua
- lua/diffview/utils.lua
- plugin/diffview.vim
The completion now works as follows:
- For arg 1, it completes commit SHA's and commit ranges.
- For 2 >= arg >= path separator, it completes flags, and flag values if the arg lead is the full name of a flag.
- For arg > path separator (`--`), it completes paths.
https://user-images.githubusercontent.com/2786478/117345695-1d57d900-aea7-11eb-8fd2-dadb6589a26f.mp4
> feat: Custom completion for `:DiffviewOpen`

- README.md
- doc/diffview.txt
- lua/diffview/config.lua
Fixes #19.
This is a breaking change. The default behavior is now to merge the user
provided key bindings with the defaults. All default key bindings can be
disabled by setting `key_bindings.disable_defaults = true`.
> feat: Merge user bindings with defaults by default.

- doc/diffview.txt
- lua/diffview/lib.lua
Fixes #33.
Currently the git root is always determined from the cwd unless the `-C` flag is defined. This changes the default behavior to try to determine the git root from the path of the current buffer when possible.
Only applies if the `-C` flag is not defined. If the current buffer is
not a readable file, the git root is determined from the cwd.
> feat: Determine git root from current buffer when possible.

- lua/diffview/config.lua
- lua/diffview/file-panel.lua
When executing commands in scripts or hotkeys, it is always better to use `<Cmd>` instead of `:`. This is because the colon raises cmdline opening events. For example, in my UI it causes weird animation.
Also `<Cmd>` is faster :)
Also I removed an extra `:` from `vim.cmd`.
> Use <Cmd> instead of :

- lua/diffview.lua
- lua/diffview/api/c-view.lua
- lua/diffview/file-panel.lua
- lua/diffview/git.lua
- lua/diffview/lib.lua
- lua/diffview/view.lua
Fixes #47.
Rev args can now use the symmetric difference notation (triple dot).
Examples:
- `:DiffviewOpen origin/main...HEAD`
- `:DiffviewOpen feat/foobar...`
Also changes the "Showing changes for:" section of the file panel. It will now show the given rev arg rather than the parsed commit SHA's.
> feat: Support symmetric difference notation.

- README.md
- doc/diffview.txt
- lua/diffview.lua
- lua/diffview/config.lua
- lua/diffview/git.lua
- lua/diffview/utils.lua
Fixes #43.
This implements file restoration: if the right side of the diff is showing the local state of the file, you can restore the file to the state from the left side of the diff (key binding `X` from the file panel by default). Staged changes are restored from `HEAD`.
> feat: Restore files

- README.md
- doc/diffview.txt
- lua/diffview.lua
- lua/diffview/lib.lua
Fixes #40.
This makes it such that most of the file panel mappings should also work from the view if they are added to the view bindings (and vice versa). The exception is for mappings that only really make sense specifically in the file panel, such as `next_entry`, `prev_entry`, and `select_entry`. Functions such as `toggle_stage_entry` and `restore_entry` work just fine from the view. When invoked from the view, these will target the file currently open in the view rather than the file under the cursor in the file panel.
> feat: Make file panel mappings also work from the view.

- lua/diffview.lua
- lua/diffview/arg_parser.lua
- lua/diffview/lib.lua
- lua/diffview/utils.lua
Fixes #54.
This fixes all the known issues with the current completion:
- Arg leads are properly taken into account.
- Rev completion now works for all symbolic revs, heads, branches, tags,
remotes, and stashes.
- Flag option completion is fixed.
- The completion also uses the current file to determine the target git
repository (the same way `:DiffviewOpen` already does).
> feat: Improved completion.

- README.md
- doc/diffview.txt
- lua/diffview/api/views/diff/diff_view.lua
- lua/diffview/colors.lua
- lua/diffview/config.lua
- lua/diffview/utils.lua
- lua/diffview/views/diff/diff_view.lua
- lua/diffview/views/file_history/file_history_view.lua
- lua/diffview/views/standard/standard_view.lua
Resolves #52.
As pointed out by @YorickPeterse, the way vim highlights diffs isn't the most intuitive when you're comparing only two files (vim has to do it this way of course, because it's the only way that makes sense when you're comparing *more* than two files).  When comparing old state on the left with new state on the right, what vim highlights as an addition on the left, actually represents a deletion.
This PR adds a new option `enhanced_diff_hl` that attempts to tackle this issue. When enabled, a couple new highlighting groups will be generated based on your colorscheme. These will be applied as local `winhl` in the diff buffers.
```vimhelp
enhanced_diff_hl                            *diffview-config-enhanced_diff_hl*
Type: `boolean`, Default: `false`
Enable/disable enhanced diff …
```
> feat: Implement enhanced diff highlighting.

- README.md
- doc/diffview.txt
- lua/diffview/views/diff/listeners.lua
- lua/diffview/views/file_history/listeners.lua
Both `select_next_entry` and `select_prev_entry` do not change cursor position. To be consistent with this behavior, I think it would be best to not move the cursor when calling `select_entry`.
Alternatively, we can define a new function to preserve existing behavior. That said, I find myself visually browsing diffs more often than I need to move my cursor into the diffs, so I think this is a reasonable default.
> Do not change cursor position on select_entry

- README.md
- doc/diffview.txt
- lua/diffview.lua
- lua/diffview/api/views/file_entry.lua
- lua/diffview/bootstrap.lua
- lua/diffview/config.lua
- lua/diffview/events.lua
- lua/diffview/lib.lua
- lua/diffview/views/file_entry.lua
- lua/diffview/views/standard/standard_view.lua
- lua/diffview/views/view.lua
Resolves #75.
The `hooks` table in the config allows you to define callbacks for various
events emitted from Diffview. The available hooks are documented in detail in
`:h diffview-config-hooks`.
The hook events are also available as User autocommands. See 
`:h diffview-user-autocmds` for more details.
```vimhelp
hooks                                                  *diffview-config-hooks*
Type: `table<string, function>`, Default: `{}`
This is a table of event names mapped to callback functions. The
callbacks are called when the related events are emitted from
Diffview.
Available Events:~
{view_opened} (`fun(view: View)`)
Emitted after a new view has been opened. It's called
after initializing the layout in the new tabpage (all
windows are ready).
Callback Parameters:~
{view} (`View`)
The …
```
> feat: Hooks

- lua/diffview.lua
- lua/diffview/api/views/diff/diff_view.lua
- lua/diffview/api/views/file_entry.lua
- lua/diffview/git/utils.lua
- lua/diffview/lib.lua
- lua/diffview/path.lua
- lua/diffview/utils.lua
- lua/diffview/views/diff/diff_view.lua
- lua/diffview/views/diff/listeners.lua
- lua/diffview/views/diff/render.lua
- lua/diffview/views/file_entry.lua
- lua/diffview/views/file_history/listeners.lua
- lua/diffview/views/file_history/render.lua
- lua/diffview/views/file_tree/file_tree.lua
Fixes #101.
This let's us ensure UNIX paths everywhere which makes cross platform path handling a lot easier. Git does not handle windows style paths for things like i.e. pathspec. But nvim,  libuv  and git does support UNIX style paths even on windows.
Another benefit from avoiding the `vim.fn.*` functions for path handling is that the path lib can be used in libuv callbacks without scheduling.
> Path library

- README.md
- doc/diffview.txt
- lua/diffview.lua
- lua/diffview/arg_parser.lua
- lua/diffview/git/utils.lua
- lua/diffview/lib.lua
- lua/diffview/path.lua
- lua/diffview/views/file_history/file_history_panel.lua
- lua/diffview/views/file_history/file_history_view.lua
- lua/diffview/views/file_history/render.lua
- plugin/diffview.vim
Resolves #95.
You can now specify the base rev for the `:DiffviewFileHistory` command by using
the `--base` flag. This will keep the state of the file on the right side of the
diff split constant as you go through commits in the history.
```vimhelp
--base={git-rev}
Specify a base git rev from which the right side of
the diff will be created. Use the special value
`LOCAL` to use the local version of the file.
```
- `:DiffviewFileHistory --base=HEAD~4`
- `:DiffviewFileHistory --base=LOCAL`
- (feat) Better completion for individual flags. I.e. the 'C' flag now provides
directory completion.
- (feat) File history now supports the 'C' flag.
- (fix) Detection of single-file file history.
> feat: Specify any git rev as a base for file history.

- lua/diffview/views/file_entry.lua
Users may have `set nofoldenable` option in their vimrc, in which case
the diff view windows will not have fold when opening. The `foldenable`
option therefore needs to be explicitly set.
> fix: Explicitly set foldenable for the diff view

- README.md
- doc/diffview.txt
- doc/diffview_changelog.txt
- lua/diffview/api/views/file_entry.lua
- lua/diffview/config.lua
- lua/diffview/events.lua
- lua/diffview/git/file_dict.lua
- lua/diffview/git/rev.lua
- lua/diffview/git/utils.lua
- lua/diffview/lib.lua
- lua/diffview/path.lua
- lua/diffview/renderer.lua
- lua/diffview/ui/model.lua
- lua/diffview/ui/models/file_tree/file_tree.lua
- lua/diffview/ui/models/file_tree/node.lua
- lua/diffview/ui/panel.lua
- lua/diffview/ui/panels/commit_log_panel.lua
- lua/diffview/utils.lua
- lua/diffview/views/diff/diff_view.lua
- lua/diffview/views/diff/file_panel.lua
- lua/diffview/views/diff/listeners.lua
- lua/diffview/views/diff/render.lua
- lua/diffview/views/file_entry.lua
- lua/diffview/views/file_history/file_history_panel.lua
- lua/diffview/views/file_history/file_history_view.lua
- lua/diffview/views/file_history/listeners.lua
- lua/diffview/views/file_history/option_panel.lua
- lua/diffview/views/file_history/render.lua
- lua/diffview/views/standard/standard_view.lua
Resolves #117.
This implements a commit log panel that lets you open a window with the full
commit descriptions for the range of git revs currently being diffed. This works
in both standard diffviews and file history views. From either the file panel,
or the file history panel, press `L` to open the commit log. In the file history
panel this will target the commit under the cursor.
The PR also refactors the internal representation of a panel (the various
interactive windows used in the plugin). Among other things, this allows all
panels to be configured as floating windows if so desired. The way panels are
configured has been changed and extended in a manner that is incompatible with
the way it was done before. To update your config, just move all the window
related options into a new …
> BREAKING CHANGE: Commit log panel and new config for panels

- README.md
- doc/diffview.txt
- doc/diffview_changelog.txt
- lua/diffview.lua
- lua/diffview/bootstrap.lua
- lua/diffview/config.lua
- lua/diffview/ui/panel.lua
- lua/diffview/ui/panels/commit_log_panel.lua
- lua/diffview/views/diff/file_panel.lua
- lua/diffview/views/file_entry.lua
- lua/diffview/views/file_history/file_history_panel.lua
- lua/diffview/views/file_history/listeners.lua
- lua/diffview/views/file_history/option_panel.lua
- plugin/diffview.vim
This PR refactors the keymap implementation to make it possible to create
mappings for modes other than normal-mode, and lets you map directly to lua
functions. The normal mode mappings can be declared the same way as before, the
only difference being that you can also map to lua functions:
```lua
view = {
-- Vim command:
["a"] = "<Cmd>echom 'foo'<CR>",
-- Lua function:
["b"] = function() print("bar") end,
}
```
For more control (i.e. mappings for other modes), you can also define
index values as list-like tables containing the args for
`:h vim.keymap.set()`. This way you can also change all the
`:h :map-arguments` with the only exception being the `buffer` field, as
this will be overridden with the target buffer number:
```lua
view = {
-- Normal and visual mode mapping to vim command:
{ …
```
> break: Refactor keymaps.

- lua/diffview/colors.lua
- lua/diffview/views/diff/file_panel.lua
- lua/diffview/views/file_history/file_history_panel.lua
- lua/diffview/views/file_history/option_panel.lua
This adds the highlight group for WinSeparator, which has superseded VertSplit. This allows the border between the Diffview panel and the buffer window to be changed without changing the border between buffer windows.
> chore: Add highlight group for WinSeparator.

- README.md
Relates to #154. The `:DiffviewFileHistory` command will not work prior to this version of Git.
> Specify git version in README

- README.md
- doc/diffview.txt
- lua/diffview/config.lua
- lua/diffview/git/commit.lua
- lua/diffview/git/rev.lua
- lua/diffview/git/utils.lua
- lua/diffview/init.lua
- lua/diffview/lib.lua
- lua/diffview/views/diff/listeners.lua
Fixes #158.
This allows you to configure the git command as well as default args used by all git jobs internally in the plugin.
```vimhelp
git_cmd                                         *diffview-config-git_cmd*
Type: `string[]`, Default: `{ "git" }`
This table forms the first part of all git commands used internally in
the plugin. The first element should be the git binary. The subsequent
elements are passed as arguments.
```
> feat: Configure the git command.

- README.md
- doc/diffview.txt
- doc/diffview_changelog.txt
- lua/diffview/arg_parser.lua
- lua/diffview/bootstrap.lua
- lua/diffview/config.lua
- lua/diffview/git/log_entry.lua
- lua/diffview/git/utils.lua
- lua/diffview/init.lua
- lua/diffview/lib.lua
- lua/diffview/utils.lua
- lua/diffview/views/file_history/file_history_view.lua
- lua/diffview/views/file_history/listeners.lua
- lua/diffview/views/file_history/option_panel.lua
- lua/diffview/views/file_history/render.lua
- plugin/diffview.lua
Resolves #114.
This implements git-log's `-L` flag, which lets you trace the evolution of a given line range.
```vimhelp
-L{start},{end}:{file}, -L:{funcname}:{file}
Trace the evolution of the line range given by
{start},{end}, or by the function name regex
{funcname}, within the {file}. You can specify this
option more than once.
```
There are multiple ways of invoking line tracing. One way is to pass it as a flag option to `:DiffviewFileHistory`. You may specify this option more than once:
```
:DiffviewFileHistory -L300,500:some/example/file -L:some\ func:other/example/file
```
Another way is to specify an EX command range. This way, the file history will trace the line evolution of the given range in the current file:
```vim
" Trace the line evolution of the visual selection in the …
```
> feat(file-history)!: Trace line evolution

- lua/diffview/vcs/adapters/git/init.lua
`path` should be put in `cwd`, otherwise got "Not a repo" error when the file was in another git repo.
> fix: Regression in finding top-level

- doc/diffview.txt
- lua/diffview/config.lua
- lua/diffview/vcs/adapters/git/init.lua
(resolves #244)
This adds the git-pickaxe options to file history. Git-pickaxe allows you to filter commits to the subset that has patch text matching a given pattern (regex). These options are available both as flag options passed to `:DiffviewFileHistory` and through the file history option panel.
```vimhelp
*:DiffviewFileHistory*
:[range]DiffviewFileHistory [paths] [options]
...
Options:~
...
-G{pattern}     Look for differences whose patch text contains
added/removed lines that match {pattern} (extended
regular expression).
-S{pattern}     Look for differences that change the number of
occurences of the specified {pattern} (extended
regular expression) in a file.
```
> feat(file-history): Add git-pickaxe options.

- .luarc.json
- README.md
- doc/diffview.txt
- doc/diffview_defaults.txt
- lua/diffview/config.lua
- lua/diffview/scene/file_entry.lua
- lua/diffview/scene/views/diff/diff_view.lua
- lua/diffview/scene/views/standard/standard_view.lua
- lua/diffview/scene/window.lua
- lua/diffview/vcs/adapter.lua
- lua/diffview/vcs/adapters/git/init.lua
- lua/diffview/vcs/adapters/git/rev.lua
- lua/diffview/vcs/file.lua
- lua/diffview/vcs/rev.lua
Resolves #282 
```vimhelp
view.x.winbar_info                              *diffview-config-view.x.winbar_info*
Type: `boolean`, Default: (see example config above)
Use the 'winbar' to show contextual info about the different versions
of a file in a diff.
```
> feat: Show context for merge conflicts in the winbar

- lua/diffview/arg_parser.lua
- lua/diffview/init.lua
- lua/diffview/scene/views/file_history/listeners.lua
- lua/diffview/scene/views/file_history/option_panel.lua
- lua/diffview/scene/views/file_history/render.lua
- lua/diffview/vcs/adapter.lua
- lua/diffview/vcs/adapters/git/init.lua
- lua/diffview/vcs/flag_option.lua
- lua/diffview/vcs/utils.lua
- plugin/diffview.lua
Resolves #272.
Everything between a pair of quotes will now be treated as part of a single argument. Example:
```
:DiffviewFileHistory --grep="foo bar baz" -G"lorem ipsum dolor"
:DiffviewOpen 'HEAD@{4 days ago}'
```
> feat: Support quoted arguments.

- lua/diffview/actions.lua
- lua/diffview/config.lua
- lua/diffview/scanner.lua
- lua/diffview/scene/file_entry.lua
- lua/diffview/scene/layout.lua
- lua/diffview/scene/views/diff/diff_view.lua
- lua/diffview/scene/views/diff/listeners.lua
- lua/diffview/scene/views/file_history/file_history_view.lua
- lua/diffview/scene/views/file_history/listeners.lua
- lua/diffview/scene/window.lua
- lua/diffview/utils.lua
- lua/diffview/vcs/adapters/git/init.lua
- lua/diffview/vcs/commit.lua
- lua/diffview/vcs/file.lua
- lua/diffview/vcs/log_entry.lua
- lua/diffview/vcs/utils.lua
When tracing line evolution (the `-L` flag option) we look at the diff patches Git outputs in order to determine what the relevant content is. We then hide the irrelevant content by setting `foldmethod=manual` in all the diff buffers and creating custom folds derived from the hunks in the git diff.
This seems to work quite well in most cases, and makes it a lot more efficient to review changes with the `-L` flag, as we no longer need to guess where in the file the change occurred. After all, Git knows this far better than us.
Bonus change: the `scroll_view()` action now uses the window that currently has the most visible content, to scroll. This makes the scrolling far less jumpy in cases where you have a large deleted hunk. As the cursor cannot be placed inside a region of filler lines, …
> feat(file-history): Hide unrelated changes when tracing line evolution

- lua/diffview/scene/views/standard/standard_view.lua
When running `DiffviewOpen` on a merge conflict I get the following error:
``` 
The coroutine failed with this message: ...nvim/lua/diffview/scene/views/standard/s
tandard_view.lua:143: attempt to index a nil value                                                                                                                                            
stack traceback:                                                                                                                                                                              
[C]: in function 'error'                                                                                                                                                              
...share/nvim/lazy/plenary.nvim/lua/plenary/async/async.lua:18: in …
```
> fix: use correct diff layout

- lua/diffview/init.lua
Resolves #369.
I have left some question here:
1. Added a comment not related to this pr, sorry if this makes you uncomfortable I will restore it.
2. I'm not sure if the fetch_tabnr's *name* is correct.
3. I'm not sure if fetch_tabnr is in the right place for this, I tried to throw it into *utils* but its logic is not that common.
> fix: Workaround for `<afile>` expanding incorrectly

- USAGE.md
A more intuitive way of commit. Just one keystroke after stash right in diffview
> docs: Add commit example using `vim.ui.input()`

- lua/diffview/vcs/adapters/git/init.lua
I noticed that the `:DiffviewOpen ..commit --imply-local` didn't show all the diffs I was expecting, and only shows diffs for files that were modified in the working copy - or indeed no diffs if the working copy is clean.
`:DiffviewOpen commit --imply-local` does work, the only difference being that it puts the `commit` files on the left, not the right.
Also, `:DiffviewOpen origin/master..commit --imply-local` fails in the same way as `:DiffviewOpen ..commit --imply-local`, but only when your checked out commit is the same as `origin/master` (this is what confused me originally!)
Anyway, it turns out we were just missing a case where the left-hand-side of the diff is local and the right-hand-side is a commit, so I've added that in this PR.
> fix: Handle rev ranges that resolve to `LOCAL..{REV}`

- .luarc.json
- lua/diffview/hl.lua
- lua/diffview/lib.lua
- lua/diffview/oop.lua
- lua/diffview/utils.lua
- **fix: remove deprecated use of vim.tbl_add_reverse_lookup**
- **fix: add VIMRUNTIME to .luarc.json**
> fix: handle deprecated util 'tbl_add_reverse_lookup()'

- lua/diffview/lib.lua
- lua/diffview/logger.lua
- lua/diffview/multi_job.lua
- lua/diffview/stream.lua
- lua/diffview/utils.lua
- lua/diffview/vcs/adapter.lua
- lua/diffview/vcs/adapters/git/init.lua
- lua/diffview/vcs/adapters/hg/init.lua
Resolves #488.
Neovim nightly deprecated some table operations resulting in diffview.nvim crashes. I've moved the operations `islist` and `flatten` to the utils package so that we can apply the appropriate function depending on the Neovim version.
Please let me know what you think, thanks!
> fix: replace deprecated table operations for neovim v0.10

- lua/diffview/vcs/file.lua
Instead one should use vim.diagnostic.enable in the following form:
vim.diagnostic.enable(true | false, { bufnr = BUFFER })
> fix: `vim.diagnostic.disable` is deprecated

- lua/diffview/vcs/adapters/git/init.lua
Otherwise, files that was included in gitignore (but added via `git add --force`) will be treated as binary and not showing diff.
> fix(git): add `--no-exclude-standard` when detecting binary

- lua/diffview/scene/views/diff/diff_view.lua
- lua/diffview/scene/views/diff/listeners.lua
Fixes #462.
I work in a large monorepo and noticed that when :DiffviewOpen was used, and you switched to another tab, you would switch back to the Diffview window.
Reason for this being that inside the async function `DiffView:update_file()`, it is possible for the line `local err, new_files = await(self:get_updated_files())` to take a long amount of time in large git repos. This meant it's possible for a user to switch to another tab prior to the async function completing, in which at the end of the function the user's window is switched to the DiffView.
I'm not entirely familiar with Lua but I made a very rough PR that changes the order of when re-rendering the panels work to abate this issue.
> fix: cancel update if view becomes out of focus

- lua/diffview/utils.lua
fixes #473
vim.notify allows the user to customize the display of messages
I'm not sure about the schedule parameter, whether it's still needed. I left it in just in case.
The testing I performed is that I triggered the:
> "The file is open with unsaved changes! Aborting file restoration."
message, by modifying a file, saving, modifying again, then asking to revert the changes in diffview, that triggered that message. I also tried modifying the location where the message is triggered to ask to trigger it with the schedule parameter being "true" and that worked too.
> feat: use `vim.notify` for user notifications
